#!/usr/bin/env python3
"""Run the scheduled YouTube outlier scans and write a Markdown report.

The input JSON is generated by the scheduled ChatGPT task.  This runner keeps
the YouTube API key in an environment variable and never writes it to disk.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from youtube_outlier import (
    ApiError,
    DAILY_QUOTA,
    QuotaTracker,
    YouTubeClient,
    assign_ranks_and_order,
    build_rows,
    load_routine_usage,
    record_routine_usage,
    save_routine_search_to_history,
)


KST = ZoneInfo("Asia/Seoul")
SHALLOW_RESULTS = 50
DEEP_RESULTS = 150
SCORE_THRESHOLD = 20.0
SAFETY_RESERVE = 250


@dataclass(frozen=True)
class ModeConfig:
    title: str
    deep_count: int
    min_subscribers: int
    max_subscribers: int
    min_views: int


CONFIGS = {
    "celebrity": ModeConfig(
        title="유튜브 셀럽훅 쇼츠 영상 발굴 리포트",
        deep_count=16,
        min_subscribers=200,
        max_subscribers=3000,
        min_views=30000,
    ),
    "trending": ModeConfig(
        title="유튜브 떡상 키워드 발굴 리포트 (한국·다양한 주제)",
        deep_count=15,
        min_subscribers=100,
        max_subscribers=1000,
        min_views=0,
    ),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=CONFIGS, required=True)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--archive-dir", type=Path, required=True)
    return parser.parse_args()


def load_keywords(path: Path, mode: str) -> tuple[list[dict[str, str]], dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("mode") != mode:
        raise ValueError(f"입력 mode가 일치하지 않습니다: {data.get('mode')!r}")

    raw = data.get("keywords")
    if not isinstance(raw, list) or len(raw) != 40:
        raise ValueError("keywords는 정확히 40개여야 합니다.")

    items: list[dict[str, str]] = []
    seen: set[str] = set()
    for index, item in enumerate(raw, start=1):
        if isinstance(item, str):
            keyword, category, reason = item, "", ""
        elif isinstance(item, dict):
            keyword = str(item.get("keyword", "")).strip()
            category = str(item.get("category", item.get("area", ""))).strip()
            reason = str(item.get("reason", "")).strip()
        else:
            raise ValueError(f"{index}번째 키워드 형식이 잘못되었습니다.")
        if not keyword or keyword in seen:
            raise ValueError(f"비어 있거나 중복된 키워드가 있습니다: {keyword!r}")
        seen.add(keyword)
        items.append({"keyword": keyword, "category": category, "reason": reason})
    return items, data


def estimated_units(max_results: int) -> int:
    pages = math.ceil(max_results / 50)
    return pages * 102  # search.list 100 + videos.list 1 + channels.list 1


def filtered_rows(rows: list[dict[str, Any]], cfg: ModeConfig) -> list[dict[str, Any]]:
    kept = []
    for row in rows:
        subscribers = row["subscriber_count"]
        if subscribers is None:
            continue
        if subscribers < cfg.min_subscribers or subscribers > cfg.max_subscribers:
            continue
        if row["view_count"] < cfg.min_views:
            continue
        kept.append(row)
    return assign_ranks_and_order(kept, "score")


def scan_keyword(
    client: YouTubeClient,
    quota: QuotaTracker,
    keyword: str,
    max_results: int,
    cfg: ModeConfig,
) -> tuple[list[dict[str, Any]], int]:
    before = quota.total_units
    published_after = (
        (datetime.now(timezone.utc) - timedelta(days=30))
        .isoformat()
        .replace("+00:00", "Z")
    )
    ids = client.search_video_ids(
        keyword,
        "viewCount",
        max_results,
        published_after=published_after,
        region_code="KR",
        relevance_language="ko",
    )
    if not ids:
        return [], quota.total_units - before
    videos = client.get_videos_details(ids)
    channel_ids = sorted({video["channel_id"] for video in videos.values()})
    channels = client.get_channels_details(channel_ids)
    rows = filtered_rows(build_rows(videos, channels, "simple"), cfg)
    return rows, quota.total_units - before


def history_options(max_results: int, cfg: ModeConfig) -> dict[str, Any]:
    return {
        "order": "viewCount",
        "sort_by": "score",
        "max_results": max_results,
        "days": 30,
        "min_views": cfg.min_views,
        "min_subscribers": cfg.min_subscribers,
        "max_subscribers": cfg.max_subscribers,
        "score_mode": "simple",
        "region": "KR",
        "language": "ko",
    }


def md(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def number(value: int | None) -> str:
    return "N/A" if value is None else f"{value:,}"


def score(value: float | None) -> str:
    return "N/A" if value is None else f"{value:.2f}"


def video_table(rows: list[dict[str, Any]]) -> list[str]:
    lines = [
        "| 순위 | 제목 | 채널 | 구독자 | 조회수 | 점수 | 게시일 |",
        "|---:|---|---|---:|---:|---:|---|",
    ]
    for row in rows[:5]:
        title = f"[{md(row['title'])}]({row['url']})"
        lines.append(
            f"| {row['rank']} | {title} | {md(row['channel_title'])} | "
            f"{number(row['subscriber_count'])} | {number(row['view_count'])} | "
            f"{score(row['score'])} | {row['published_at'].astimezone(KST):%Y-%m-%d} |"
        )
    return lines


def build_report(
    mode: str,
    source: dict[str, Any],
    rankings: list[dict[str, Any]],
    details: dict[str, dict[str, Any]],
    quota_before: int,
    quota_used: int,
    failures: list[str],
) -> str:
    cfg = CONFIGS[mode]
    now = datetime.now(KST)
    lines = [
        f"# {cfg.title} ({now:%Y-%m-%d})",
        "",
        "> 이 리포트는 미래 예측이 아니라, 최근 유튜브 데이터에 이미 나타난 신호를 찾은 결과입니다.",
        "",
        f"- 생성 시각: {now:%Y-%m-%d %H:%M} KST",
        f"- 키워드 생성 시각: {source.get('generated_at', '미기재')}",
        f"- 이번 실행 사용량: **{quota_used:,}유닛**",
        f"- 오늘 루틴 누적 사용량: **{quota_before + quota_used:,} / {DAILY_QUOTA:,}유닛**",
        f"- 검색 프로필: 얕은 스캔 {SHALLOW_RESULTS}개 / 딥다이브 {DEEP_RESULTS}개 / 최근 30일 / KR·ko",
        "",
        "## 키워드 랭킹",
        "",
        "| 순위 | 키워드 | 영역 | 결과수 | 점수 20↑ | 최고점수 | 딥다이브 |",
        "|---:|---|---|---:|---:|---:|---|",
    ]
    for rank, item in enumerate(rankings, start=1):
        lines.append(
            f"| {rank} | {md(item['keyword'])} | {md(item['category'] or '-')} | "
            f"{item['result_count']} | {item['signals']} | {score(item['max_score'])} | "
            f"{'완료' if item['keyword'] in details else '-'} |"
        )

    lines.extend(["", "## 딥다이브 상세", ""])
    for item in rankings:
        keyword = item["keyword"]
        if keyword not in details:
            continue
        detail = details[keyword]
        rows = detail["rows"]
        lines.extend(
            [
                f"### {md(keyword)}",
                "",
                f"선정 이유: 얕은 스캔에서 점수 20 이상 {item['signals']}개, 최고점수 {score(item['max_score'])}.",
                "",
            ]
        )
        if rows:
            top = rows[0]
            lines.append(
                f"**1위:** [{md(top['title'])}]({top['url']}) — {md(top['channel_title'])}, "
                f"구독자 {number(top['subscriber_count'])}, 조회수 {number(top['view_count'])}, "
                f"점수 {score(top['score'])}"
            )
            lines.extend(["", *video_table(rows), ""])
            if mode == "celebrity":
                lines.append(
                    "패턴 코멘트: 제목에서 셀럽·상품 훅은 확인할 수 있지만, 상품명 숨김 및 제휴태그는 "
                    "YouTube Data API의 현재 수집 항목만으로 확정할 수 없어 원문 확인이 필요합니다."
                )
        else:
            lines.append("딥다이브 필터 조건을 만족하는 영상이 없습니다.")
        lines.append("")

    if failures:
        lines.extend(["## 실패·건너뜀", ""])
        lines.extend(f"- {md(item)}" for item in failures)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    args = parse_args()
    api_key = os.environ.get("YOUTUBE_API_KEY")
    if not api_key:
        print("YOUTUBE_API_KEY GitHub Secret이 필요합니다.", file=sys.stderr)
        return 2

    cfg = CONFIGS[args.mode]
    keywords, source = load_keywords(args.input, args.mode)
    quota_before = int(load_routine_usage().get("units_used", 0))
    available = max(DAILY_QUOTA - quota_before - SAFETY_RESERVE, 0)
    quota = QuotaTracker()
    client = YouTubeClient(api_key, quota)
    rankings: list[dict[str, Any]] = []
    failures: list[str] = []

    for item in keywords:
        keyword = item["keyword"]
        if quota.total_units + estimated_units(SHALLOW_RESULTS) > available:
            failures.append(f"{keyword}: 일일 할당량 안전 한도로 건너뜀")
            rankings.append({**item, "result_count": 0, "signals": 0, "max_score": None})
            continue
        try:
            rows, used = scan_keyword(client, quota, keyword, SHALLOW_RESULTS, cfg)
            save_routine_search_to_history(keyword, history_options(SHALLOW_RESULTS, cfg), rows, used)
            scores = [row["score"] for row in rows if row["score"] is not None]
            rankings.append(
                {
                    **item,
                    "result_count": len(rows),
                    "signals": sum(value >= SCORE_THRESHOLD for value in scores),
                    "max_score": max(scores, default=None),
                }
            )
        except ApiError as exc:
            failures.append(f"{keyword}: {exc}")
            rankings.append({**item, "result_count": 0, "signals": 0, "max_score": None})

    rankings.sort(
        key=lambda item: (item["signals"], item["max_score"] or -1),
        reverse=True,
    )

    details: dict[str, dict[str, Any]] = {}
    candidates = rankings[: cfg.deep_count]
    for item in candidates:
        keyword = item["keyword"]
        if quota.total_units + estimated_units(DEEP_RESULTS) > available:
            failures.append(f"{keyword}: 딥다이브 할당량 부족으로 건너뜀")
            continue
        try:
            rows, used = scan_keyword(client, quota, keyword, DEEP_RESULTS, cfg)
            save_routine_search_to_history(keyword, history_options(DEEP_RESULTS, cfg), rows, used)
            details[keyword] = {"rows": rows}
        except ApiError as exc:
            failures.append(f"{keyword} 딥다이브: {exc}")

    report = build_report(
        args.mode,
        source,
        rankings,
        details,
        quota_before,
        quota.total_units,
        failures,
    )
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(report, encoding="utf-8")
    archive = args.archive_dir / args.mode / f"{datetime.now(KST):%Y-%m-%d_%H%M}.md"
    archive.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(args.report, archive)
    cumulative = record_routine_usage(quota.total_units)
    print(f"리포트 저장: {args.report}")
    print(f"이번 실행: {quota.total_units}유닛 / 오늘 누적: {cumulative}유닛")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
